### ISSUE TITLE
What if `document.createElement` is overridden?

### ISSUE THREAD

**Issue by zjuchenyuan** [perry-mitchell/slyfox#6]
HTML for testing:

```html
<script>
    document.createElement=function(){}
</script>
<script src="archetype.js"></script>
<script>
archetype.onReady(function() {

    var getElementById = archetype.getNativeMethod("document.getElementById");
    console.log(getElementById)

});
</script>
```

this code throws Exception:

```
archetype.js:57 Uncaught TypeError: Cannot read property 'style' of undefined
    at prepareIframe (archetype.js:57)
    at archetype.js:62
    at HTMLDocument.evtListener (archetype.js:33)

test.html:8 Uncaught TypeError: archetype.getNativeMethod is not a function
    at test.html:8
    at archetype.js:44
```

**Comment by perry-mitchell** [comment]
Good point - I wonder if we’re getting to some limitation by overriding potentially every native method archetype requires to run.. Would you happen to have any suggestions as to how we could improve this functionality?

At some point overriding a method will prove fatal to the page working properly.. if I call createElement and don’t receive an element.. that’s a sad state of affairs. I also haven’t seen a lib (eg. prototype) break createElement before.. but would be happy to see any examples in the wild.

**Comment by zjuchenyuan** [comment]
if just document.createElement is overridden, we can recover it using `Document.prototype`:

```
document.createElement=Document.prototype.createElement
```

But this doesn't work if `Document.prototype.createElement` also been overridden.

I just wondering this javascript overridden behaviour is recoverable in theory. 

----

It seems your project is meant for website developing, not hacking. My startpoint is this page: Image Protection: Serverside Encryption & Clientside Decryption
https://www.patrick-wied.at/talks/image-protection/demos/demo-encrypted.html

In this page canvas.toDataURL is overridden to protect the image. But I found we can do this in `Developer Tools`, just like what `archetype` do:

```
var i = document.createElement('iframe');
i.style.display = 'none';
document.body.appendChild(i);
var c=i.contentDocument.createElement("canvas")
c.toDataURL.call(document.getElementsByTagName("canvas")[0])
```

Then I am wondering what if `document.createElement` is not available for creating a new iframe? Still any method to call original native functions?

In this anti-anti-crawler scenario, there may be more available and easier choices:

* ask the web browser to execute our code before any page code
* just do element screenshot

**Comment by zjuchenyuan** [comment]
If we can execute javascript code before any other scripts that override desired function, we can do this: (take canvas `toDataURL` as a example)

```
const getOriginalFunction = Function.prototype.call.bind(
 Function.prototype.bind,
 Function.prototype.call
);
const originalToDataURL = getOriginalFunction(HTMLCanvasElement.prototype.toDataURL);
```

this code is copied from: https://www.usenix.org/sites/default/files/conference/protected-files/security18_slides_vastel.pdf

then, we can call `originalToDataURL`
![image](https://user-images.githubusercontent.com/17289004/47612600-2a670680-dab9-11e8-8b87-6cb1f742595e.png)

**Comment by perry-mitchell** [comment]
I like the idea, but archetype was designed for contexts where the items being restored are **already overwritten**, and need to be restored. Archetype is restorative and not preventative.

I'm not sure how likely these scenarios are. For instance, who would go to the trouble of overwriting a document method _and_ its prototype? In this case, wouldn't it be better to fix the entire website rather than try to monkey-patch the entire thing with archetype? 😅
